name: amplitude_experiments_flutter
description: >-
  Flutter SDK for Amplitude Experiment. Provides feature flags and A/B testing
  capabilities with native iOS and Android support.
version: 0.0.1
homepage: https://amplitude.com/docs/sdks/experiment-sdks
repository: https://github.com/kaiquegazola/amplitude_experiments_flutter

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  amplitude_experiments_flutter_android: ^0.0.1
  amplitude_experiments_flutter_ios: ^0.0.1
  amplitude_experiments_flutter_platform_interface: ^0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: amplitude_experiments_flutter_android
      ios:
        default_package: amplitude_experiments_flutter_ios
