name: amplitude_experiments_flutter_ios
description: >-
  iOS implementation of the amplitude_experiments_flutter plugin.
  Uses the native Amplitude Experiment iOS SDK via CocoaPods.
version: 0.0.1+1
homepage: https://amplitude.com/docs/sdks/experiment-sdks
repository: https://github.com/kaiquegazola/amplitude_experiments_flutter

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  amplitude_experiments_flutter_platform_interface: ^0.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: amplitude_experiments_flutter
    platforms:
      ios:
        pluginClass: AmplitudeExperimentsFlutterPlugin
        dartPluginClass: AmplitudeExperimentsFlutterIOS
